export enum MENUS_NAME {
  DASHBOARD = 'DASHBOARD',

  PROJECT = 'PROJECT',
  PROJECT_LIST = 'PROJECT_LIST',
  ADD_PROJECT = 'ADD_PROJECT',

  TASK = 'TASK',
  TASK_LIST = 'TASK_LIST',
  ADD_TASK = 'ADD_TASK',

  PERSONNEL_MANAGEMENT = 'PERSONNEL_MANAGEMENT',
  CANDIDATE_LIST = 'CANDIDATE_LIST',
  ADD_CANDIDATE = 'ADD_CANDIDATE',

  SYSTEM_MANAGEMENT = 'SYSTEM_MANAGEMENT',
  USER_GROUP_LIST = 'USER_GROUP_LIST',
  USER_GROUP_DETAIL = 'USER_GROUP_DETAIL',
  ADD_USER_GROUP = 'ADD_USER_GROUP',
  USER_LIST = 'USER_LIST',
  USER_DETAIL = 'USER_DETAIL',
  ADD_USER = 'ADD_USER',
  ROLE_LIST = 'ROLE LIST',
  ROLE_DETAIL = 'ROLE_DETAIL',
  ADD_ROLE = 'ADD_ROLE',
}
