export enum PAGES_NAME {
  HOME = 'HOME',

  SIGN_IN = 'SIGN_IN',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',

  PROFILE = 'PROFILE',

  PROJECT = 'PROJECT',
  PROJECT_LIST = 'PROJECT_LIST',
  PROJECT_DETAIL = 'PROJECT_DETAIL',
  ADD_PROJECT = 'PROJECT_CREATE',
  UPDATE_PROJECT = 'PROJECT_EDIT',

  TASK = 'TASK',
  TASK_LIST = 'WORK_LIST',
  TASK_DETAIL = 'WORK_DETAIL',
  ADD_TASK = 'WORK_CREATE',
  UPDATE_TASK = 'WORK_EDIT',

  PLAN = 'PLAN',
  PLAN_LIST = 'PLAN_LIST',
  PLAN_DETAIL = 'PLAN_DETAIL',
  ADD_PLAN = 'PLAN_CREATE',
  UPDATE_PLAN = 'PLAN_EDIT',

  JOB = 'JOB',
  JOB_LIST = 'JOB_LIST',
  JOB_DETAIL = 'JOB_DETAIL',
  ADD_JOB = 'JOB_CREATE',
  UPDATE_JOB = 'JOB_EDIT',

  PERSONNEL_MANAGEMENT = 'PERSONNEL_MANAGEMENT',
  CANDIDATE_LIST = 'CANDIDATE_LIST',
  ADD_CANDIDATE = 'ADD_CANDIDATE',

  SYSTEM_MANAGEMENT = 'SYSTEM_MANAGEMENT',

  USER_GROUP_LIST = 'GROUP_USER_LIST',
  USER_GROUP_DETAIL = 'GROUP_USER_DETAIL',
  ADD_USER_GROUP = 'GROUP_USER_CREATE',
  UPDATE_USER_GROUP = 'GROUP_USER_EDIT',

  USER_LIST = 'USER_LIST',
  USER_DETAIL = 'USER_DETAIL',
  ADD_USER = 'USER_CREATE',
  UPDATE_USER = 'USER_EDIT',

  ROLE_LIST = 'ROLE_LIST',
  UPDATE_ROLE = 'ROLE_EDIT',
  ADD_ROLE = 'ROLE_CREATE',
  ROLE_DETAIL = 'ROLE_EDIT',

  ERROR_404 = 'ERROR_404',

  ALL = 'ALL',

  // for dashboard only
  DAY_TASK = 'DAY_TASK',
}
