import { PAGES } from '@types';

export const SETTINGS_CONFIG = {
  SIGN_IN_REDIRECT_URL: PAGES.HOME,
  SIGN_OUT_REDIRECT_URL: PAGES.HOME,
  PERMISSION_REDIRECT_URL: PAGES.SIGN_IN,

  LOADING_FONTS: ['16px Arial'],

  LOGO_SIZE: '40px',

  NAVBAR_SIZE: '60px',
  EXPAND_NAVBAR_SIZE: '260px',

  TOOLBAR_HEIGHT: '60px',
};
